[tool.poetry]
name = "workspace"
version = "0.1.0"
description = ""
authors = ["Bruno Muhlmann"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.11"
transformers = "^4.44.0"
datasets = "^2.20.0"
trl = "^0.9.6"
nvitop = "^1.3.2"
bitsandbytes = "^0.43.3"
peft = "0.12.0"
torch = "^2.4.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
